apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-stage
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/savagame/GitOps-At-Scale-Multitenancy.git"
    targetRevision: main
    path: ./effective-git-repository-strategies/folders-for-environments/overlays/staging

  destination:
    server: https://kubernetes.default.svc
    namespace: stage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
